### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by richaardvark** [savbell/whisper-writer#12]
Hello,

First of all, there were issues/conflicts when installing this script with regard to "numba" and it not being compatible with the latest version of Python (3.12.0) so I had to additionally manually install Python 3.11.6 and use that version explicitly for the virtual environment but that wasn't the biggest deal.

It worked the first few times when I provided my API key and had "use_api: true," set but was very, very slow at transcribing even one or two word phrases. I then tried switching this to false to see if it would be any better and it just got stuck on "transcribing" forever. I exited the script and switched "use_api:" back to true and then tried running it again but now I'm getting the following error:

`(venv) C:\Users\rich\whisper-writer>python run.py
Starting WhisperWriter...
C:\Users\rich\whisper-writer\venv\Lib\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
Script activated. Whisper is set to run using OpenAI's API. To change this, modify the "use_api" value in the src\config.json file.
Press Ctrl+Alt+Space to start recording and transcribing. Press Ctrl+C on the terminal window to quit.
Recording...
Recording finished. Size: 9120
Transcribing audio file...
Transcription: How are you?
Exception in thread Thread-2 (process):
Traceback (most recent call last):
  File "C:\Users\rich\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\rich\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rich\whisper-writer\venv\Lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rich\whisper-writer\venv\Lib\site-packages\keyboard\__init__.py", line 218, in pre_process_event
    callback(event)
  File "C:\Users\rich\whisper-writer\venv\Lib\site-packages\keyboard\__init__.py", line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
                                                                                                                                                          ^^^^^^^^^^
  File "C:\Users\rich\whisper-writer\src\main.py", line 85, in on_shortcut
    pyautogui.write(transcribed_text, interval=config['writing_key_press_delay'])
  File "C:\Users\rich\whisper-writer\venv\Lib\site-packages\pyautogui\__init__.py", line 593, in wrapper
    failSafeCheck()
  File "C:\Users\rich\whisper-writer\venv\Lib\site-packages\pyautogui\__init__.py", line 1734, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.`

**Comment by savbell** [comment]
Hi there,

I've recently returned to this project and we've made a couple changes. We updated the Whisper package which resolves the `numba` issue. We also changed from using `pyautogui` for typing to `pynput`. Do you still run into issues when you run the program from the latest commit?

Thanks!

**Comment by distbit0** [comment]
I am having significant issues trying to install using python 3.12.

Attached is a log of all the errors I have encountered and remedial commands I have executed while installing the modules in requirements.txt in a py3.12 venv on fedora 38.

[errors.txt](https://github.com/savbell/whisper-writer/files/14160770/errors.txt)

**Comment by savbell** [comment]
Hi, apologies for the late response. Currently, the application only works on Python 3.11 and I am not planning on supporting any other versions. I would recommend [downloading a compatible version of Python](https://www.python.org/downloads/) if you would like to run WhisperWriter.

Thanks,
Sav
