### ISSUE TITLE
Issues with installation -> webrtcvad error

### ISSUE THREAD

**Issue by chriZVee** [savbell/whisper-writer#16]
Hello there,

this tool is awesome, and on one of my machines it runs very well, and on the other I still get an error while setting it up.

**What I have done so far:**
- pip install webrtcvad (results in the same error shown below)
- pip install webrtcvad-wheels (successful)
- pip install nes-py --no-cache-dir
- pip install --upgrade pip setuptools wheel
- pip3 install webrtcvad-wheels
- pip install Cmake
- reinstalled Python (using 3.11.7, on both machines)
- Python reinstall (3.11.7; 3.11.6)
- setup everything from scratch several times
- Installed & reinstalled Build tools - C++
![buildtools](https://github.com/savbell/whisper-writer/assets/149883190/5d6fc706-7442-4558-ba16-897360aad939)

**Error description**
I receive the following **error**, when I execute the command ((venv) C:\Windows\System32\whisper-writer>pip install -r requirements.txt):

Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for webrtcvad (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      copying webrtcvad.py -> build\lib.win-amd64-cpython-311
      running build_ext
      building '_webrtcvad' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\cbits
      creating build\temp.win-amd64-cpython-311\Release\cbits\webrtc
      creating build\temp.win-amd64-cpython-311\Release\cbits\webrtc\common_audio
      creating build\temp.win-amd64-cpython-311\Release\cbits\webrtc\common_audio\signal_processing
      creating build\temp.win-amd64-cpython-311\Release\cbits\webrtc\common_audio\vad
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_WIN32 -Icbits -IC:\Windows\System32\whisper-writer\venv\include -IC:\Users\lisa_\AppData\Local\Programs\Python\Python311\include -IC:\Users\lisa_\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tccbits\pywebrtcvad.c /Fobuild\temp.win-amd64-cpython-311\Release\cbits\pywebrtcvad.obj
      pywebrtcvad.c
      C:\Users\lisa_\AppData\Local\Programs\Python\Python311\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for webrtcvad
Failed to build webrtcvad
ERROR: Could not build wheels for webrtcvad, which is required to install pyproject.toml-based projects
____

Before reinstalling C++ Build Tools, the error (fatal error C1083: Cannot open include file: 'io.h': No such file or directory) was not present, but further reinstalling didn't fix it yet. The error shown above about the webrtcvad-wheels is persistent since my first tries to install it.

Do you guys have an idea, how to fix it?

Thanks for your time and support,
Chris

**Comment by josher19** [comment]
Might be fixed by #17 --- I updated the requirements.txt so it did not try to install webrtcvad twice -- instead it just used the wheels version.

If you are not using an API key, you will need to make sure rust is installed as well: 

```
winget install Rustlang.Rustup
``` 

or scoop/choco equivalent.

**Comment by savbell** [comment]
Hi, I've approved and merged #17! Thanks @josher19. Did this fix your issue @chriZVee?
