### ISSUE TITLE
initial_prompt doesn't seem to be working

### ISSUE THREAD

**Issue by felixlu07** [savbell/whisper-writer#18]
I tried setting the initial_prompt to condition the output from the whisper-1 API but it seems like the whatever that is set in the config file is not influencing the output that is returned from the API. I even tried explicitly to test by saying "insert HELLO in front of in every sentence", but it doesn't seem to be working. Is there any additional configuration that is required, or am I missing something?

**Comment by savbell** [comment]
Hi there,

The initial prompt for OpenAI's Whisper model is different than prompts for its other models such as GPT. It wasn't trained to follow instructions, so in this case a prompt is actually some sample text that is written in the same style that you would like the outputted text to be in. [Here is the official documentation](https://platform.openai.com/docs/guides/speech-to-text/prompting) that includes some examples. If you wanted to give it more explicit instructions, you can do some post-processing using the GPT models.

I hope this helps! :)

**Comment by felixlu07** [comment]
Wow, that was really useful to know anyway! That really saved me a lot of effort in correcting some of the commonly used phrases, but it is incorrectly typed out by WhisperWriter. So thanks for that. Cheers @savbell !
