### ISSUE TITLE
Requirements incomplete and device detection does not work properly

### ISSUE THREAD

**Issue by dimmingmuse** [savbell/whisper-writer#24]
1) "Auto" for device does not detect the right values or if the complete setup is available to use CUDA DNN.
2) GPU processing seems to require CUDA DNN libraries.
3) Installing CUDA DNN requires signup to NVIDIA developers.

**Comment by savbell** [comment]
Hi, thanks for the issue and apologies for the late response!

PR #30 hopefully better detects CUDA availability, and the Readme now has links to the NVIDIA libraries under the Getting Started Prerequisites.

Thanks,
Sav
