### ISSUE TITLE
Seem to don't work

### ISSUE THREAD

**Issue by DreamDrum** [savbell/whisper-writer#3]
Hello, sorry to disturb, im not good in python or other, and i just wanted to use your whisper-writer in adition to whister to do somes test and to talk in real time online in other language.
And after all installed, following the steps, the thing start but that didn't do anything except showing the rec thing, no error or anything, just he didn't write... Maybe you have a soluce ?

**Comment by DreamDrum** [comment]
"Starting WhisperWriter...
Script activated. Press Ctrl+Alt+Space to start recording and transcribing. Press Ctrl+C on the terminal window to quit.
Recording...
Recording finished. Size: 53280
Transcribing audio file...
Error: <empty message>
Recording...
Recording finished. Size: 163680
Transcribing audio file...
Error: <empty message>"

The only thing i have, didn't seem to work, for testing i checked if the mic worked, he worked, if the mic was the mic in "default" for the computer, etc

**Comment by savbell** [comment]
Hi, thank you for your comment! Apologies for taking a while to respond. I made a small update to how errors are logged in my [most recent commit](https://github.com/savbell/whisper-writer/commit/bfe27829374873fde939034c6361d8c4676b02b3#diff-c8d8f8ea5abfe6e46cdcb9c91e1178e0a795c95a950cc18e547bcd196b58ec99R119), so now more detailed information should be printed out to the console. Please update to the latest version and let me know what the detailed error is and I can help you resolve this! Also, if you could provide me what your settings are in the configuration file, that would be helpful as well. Thanks! :)

**Comment by savbell** [comment]
Closing stale issue.

**Comment by DreamDrum** [comment]
Sorry for the long time to answer, i litteraly forgot about that issue i posted a few time ago because i founded the error was mine, i litteraly forgot one step.

I tested a bit more, its working fine and you really made a good work.

Also i take benefit of this answer to ask you a question,
The thing i still don't understand actually its how to modify the "delay" the recording have before closing the rec when i stop speaking, do you integrated a command for that ?

**Comment by savbell** [comment]
Hi @DreamDrum , I'm glad to hear that you were able to resolve your issue and that the app is working for you now!

Yes, you can modify the length of the delay between when the speaker stops talking and when the app stops recording. To do this, you need to modify the `silence_duration` configuration option in [`src/config.json`](https://github.com/savbell/whisper-writer/blob/main/src/config.json). By default, it is set to 900 milliseconds, but you can increase it to make the delay longer or decrease it to make it shorter.

I hope that helps, and let me know if you run into any other issues! :)
