### ISSUE TITLE
Please add support for local whisper api

### ISSUE THREAD

**Issue by faspie** [savbell/whisper-writer#32]
[https://github.com/mudler/LocalAI](url)

Support can simly be added by 
```
import openai
openai.base_api = "http://someinternalhost.local/v1"
```
The URL should be configured by the config.json file

`"api_options": {
        "model": "whisper-1",
        "language": null,
        "temperature": 0.0,
        "initial_prompt": null
        **"base_api": "http://someinternalhost.local/v1"**
    },`

**Comment by rkilchmn** [comment]
you can also set the environment variable OPENAI_API_BASE:
export OPENAI_API_BASE=http://someinternalhost.local/v1

**Comment by savbell** [comment]
Hi, thank you for the comments! I've added support for a custom API endpoint through an environment variable in [my latest commit](https://github.com/savbell/whisper-writer/commit/2b37eb4d2d6d825d42f463d6fee74f8773e88d0c). Please let me know if you run into any issues!

Thanks,
Sav
