### ISSUE TITLE
Missing requirements: pycairo PyGObject

### ISSUE THREAD

**Issue by faspie** [savbell/whisper-writer#43]
1) First startup of WhsiperWriter fails
`Starting WhisperWriter...
Traceback (most recent call last):
  File "/home/fabian/whisper-writer/src/main.py", line 7, in <module>
    from audioplayer import AudioPlayer
  File "/home/fabian/whisper-writer/venv/lib/python3.10/site-packages/audioplayer/__init__.py", line 12, in <module>
    from .audioplayer_linux import AudioPlayerLinux as AudioPlayer
  File "/home/fabian/whisper-writer/venv/lib/python3.10/site-packages/audioplayer/audioplayer_linux.py", line 7, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
`
2) I solved the problem by adding some dependencies according to [https://stackoverflow.com/questions/71369726/no-module-named-gi](https://stackoverflow.com/questions/71369726/no-module-named-gi)

`sudo apt install libcairo2-dev libxt-dev libgirepository1.0-dev
pip install pycairo PyGObject
`
3) Now the startup fails because I am not root --> [https://github.com/savbell/whisper-writer/issues/42](https://github.com/savbell/whisper-writer/issues/42)

**Comment by savbell** [comment]
Hi, thanks for the bug report! The application was built for Python 3.11, but I noticed in your error message you were attempting to run it with 3.10. That may be causing some of your issues. If you receive the same error again when running with 3.11, please open another issue and I will see if something needs to be added to the dependencies!

Cheers,
Sav

**Comment by robcxyz** [comment]
I can confirm that on ubuntu with python 3.11 that additional deps are needed per this issue. 

```
sudo apt install libcairo2-dev libxt-dev libgirepository1.0-dev 
pip install pycairo PyGObject 
```

**Comment by seszele64** [comment]
thanks, had similar issue on arch, installed

libs mentioned by you with
```
sudo pacman -S cairo libxt gobject-introspection
```
and then installed
```
pip install pycairo PyGObject
```
and it works, thx again
