### ISSUE TITLE
Program Not Responsive after a few minutes; Require Restart

### ISSUE THREAD

**Issue by ohcrapitsmrtee** [savbell/whisper-writer#44]
When I start using the program, it seems to be working just fine. However, if I haven't used it for 20 or 30 minutes, the recording trigger button no longer works (or isn't recognized). The only way I can get the program to work again is to restart it.  Any thoughts on fixing this feature or what might be causing the bug .

Thanks

**Comment by savbell** [comment]
Hi, thanks for the bug report! I've just released a major rewrite of the application that may have solved the issue, since the activation keyboard shortcut is handled differently now. Please let me know if you are continuing to have this problem after updating to the latest version.

Cheers,
Sav

**Comment by ohcrapitsmrtee** [comment]
Tried the update. It works a lot better. Good job!
