### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by itsdeadfrosty** [savbell/whisper-writer#52]
I'm sure your instructions are really handy and easy to understand for those who are actually know how to code or commonly work with Github,

But I don't

It talks about something about a virtual environment and then the following once you did install something and the text turns red and it's not very specific on what it wants you to do so I kind of just gave up

**Comment by savbell** [comment]
Hi, thanks for your comment! I'm sorry you found the instructions to be confusing. In the future, I plan to make a standalone executable file that will be easier for people to use, but I haven't had the time to do so yet.

Red text appearing sounds like you ran into some sort of error. If you can copy and paste it here, I can help you troubleshoot. However, without knowing what it said, I'm afraid I'm not able to help you out.

Cheers,
Sav

**Comment by vikastanwar9** [comment]
this issue how can i fix 


  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Admin\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Admin\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\msvc.py", line 189, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by itsdeadfrosty** [comment]
> this issue how can i fix
> 
> Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [35 lines of output] Traceback (most recent call last): File "C:\Users\Admin\venv\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "C:\Users\Admin\venv\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\venv\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=[]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires self.run_setup() File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup super().run_setup(setup_script=setup_script) File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup exec(code, locals()) File "", line 126, in File "", line 105, in uses_msvc File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools_distutils\command\config.py", line 220, in try_compile self._compile(body, headers, include_dirs, lang) File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools_distutils\command\config.py", line 132, in _compile self.compiler.compile([src], include_dirs=include_dirs) File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools_distutils_msvccompiler.py", line 343, in compile self.initialize() File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools_distutils_msvccompiler.py", line 253, in initialize vc_env = _get_vc_env(plat_spec) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env return _msvc14_get_vc_env(plat_spec) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-oj1leede\overlay\Lib\site-packages\setuptools\msvc.py", line 189, in _msvc14_get_vc_env raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat") distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> [notice] A new release of pip is available: 24.0 -> 24.1.1 [notice] To update, run: python.exe -m pip install --upgrade pip

dude make your own issue
