### ISSUE TITLE
Pulseaudio

### ISSUE THREAD

**Issue by korjavin** [savbell/whisper-writer#7]
Is there a way to specify the device for recording?

**Comment by uberkael** [comment]
I'm using Pipewire but it will be the same, I solved it by doing this:

1. Check the device number with `python -m sounddevice` 

2. Edit src/transcription.py: line ~45~ and add your device number as **device**
`with sd.InputStream(samplerate=sample_rate, channels=1, dtype='int16', blocksize=sample_rate * frame_duration // 1000,
    device=8,
    callback=lambda indata, frames, time, status: buffer.extend(indata[:, 0])):`

I needed to change the sample rate too ie. `sample_rate = 48000` checking it with `pactl list short sinks`

![image](https://github.com/savbell/whisper-writer/assets/1783926/b402ce2b-141c-4c7d-a00d-d397045fe806)

![image](https://github.com/savbell/whisper-writer/assets/1783926/cbb41850-212b-45db-b874-c95c6516705c)

**Comment by savbell** [comment]
Hi there,

Thank you @uberkael for your response! In [my latest commit](https://github.com/savbell/whisper-writer/commit/5c10f6b84817d11cffbcdff1ab3f483819c41544), I've added config options for choosing the sound device and sample rate. :)
